services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - '${SURREALDB_PORT}:8000'
    command:
      - start
      - --log=${SURREALDB_PORT}
      - --user=${SURREALDB_USER}
      - --pass=${SURREALDB_PASS}
    restart: unless-stopped
    volumes:
      - ./surrealdb_data:/data